apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf
data:
  mysql-host: mysqlServer   # The name of mysql service
  mysql-database-name: kubernetesDb     # The name of the database used by the demo app
  mysql-port: 3306